AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 60


Resources:
    ApiGatewayApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: dev
            Cors: "'*'"
            Auth:
                DefaultAuthorizer: MyCognitoAuth 
                Authorizers:
                    MyCognitoAuth:
                        UserPoolArn: arn:aws:cognito-idp:us-east-1:265267535237:userpool/us-east-1_xmlerYTkV
                        Identity: 
                            Header: Authorization 
              
    

    HelloWorldFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: dist/hello-world/
            Handler: app.lambdaHandler
            Runtime: nodejs10.x
            Events:
                ApiEvent:
                    Type: Api 
                    Properties:
                        Path: /
                        Method: get
                        RestApiId: !Ref ApiGatewayApi


    HelloWorldFunctionSecure:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: dist/hello-world/
            Handler: app.lambdaHandler
            Runtime: nodejs10.x
            Events:
                ApiEvent:
                    Type: Api 
                    Properties:
                        Path: /Secure
                        Method: post
                        RestApiId: !Ref ApiGatewayApi
                        Auth:
                          Authorizer: MyCognitoAuth

# CREATE FOLDER 

    CreateFolder:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: dist/CreateFolder/
            Handler: app.lambdaHandler
            Runtime: nodejs10.x
            Events:
                ApiEvent:
                    Type: Api 
                    Properties:
                        Path: /S3peration/createFolder
                        Method: post
                        RestApiId: !Ref ApiGatewayApi
                        Auth:
                          Authorizer: MyCognitoAuth



# DELETE FOLDER DB

    DeleteFolder:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: dist/DeleteFolderDB/
            Handler: app.lambdaHandler
            Runtime: nodejs10.x
            Events:
                ApiEvent:
                    Type: Api 
                    Properties:
                        Path: /S3peration/deleteFolder
                        Method: delete
                        RestApiId: !Ref ApiGatewayApi
                        Auth:
                          Authorizer: MyCognitoAuth                               













    CustomLinkProvider:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: dist/CustomLinkProvider/
            Handler: app.lambdaHandler
            Runtime: nodejs10.x
            Role: arn:aws:iam::265267535237:role/LambdaFullAccessCognitp


    