AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 60


Resources:

    HelloWorldFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: dist/hello-world/
            Handler: app.lambdaHandler
            Runtime: nodejs10.x
            Events:
                HelloWorld:
                    Type: Api 
                    Properties:
                        Path: /
                        Method: get
                        RestApiId: !Ref BossUplaodApi
                        #Auth:
                          #Authorizer: MyCognitoAuth 

    CustomLinkProvider:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: dist/CustomLinkProvider/
            Handler: app.lambdaHandler
            Runtime: nodejs10.xdant
            Role: arn:aws:iam::265267535237:role/LambdaFullAccessCognitp


    BossUplaodApi:
            Type: AWS::Serverless::Api
            Properties:
            StageName: Prod
            Cors: "'*'"
            Auth:
                DefaultAuthorizer: MyCognitoAuthorizer
                Authorizers:
                    MyCognitoAuthorizer:
                        UserPoolArn: arn:aws:cognito-idp:us-east-1:265267535237:userpool/us-east-1_xmlerYTkV
                        Identity: 
                            Header: Authorization 
           
